# Generated by Django 5.2.3 on 2025-06-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('access_admin_section', 'Pode acessar a seção de Administração & Auditoria'),), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
