# Generated by Django 5.2.3 on 2025-06-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('access_admin_section', 'Pode acessar a seção de Administração & Auditoria'), ('can_request_pix', 'Pode realizar consultas de PIX'), ('can_request_ccs', 'Pode realizar consultas de CCS')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
