# Generated by Django 5.2.1 on 2025-05-16 20:44

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChavePix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_void', models.BooleanField(db_column='inativo', default=False, verbose_name='Inativo')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('chave', models.CharField(blank=True, db_column='chave', max_length=255, verbose_name='Chave')),
                ('tipo_chave', models.CharField(blank=True, db_column='tipo_chave', max_length=50, verbose_name='Tipo de Chave')),
                ('status', models.CharField(blank=True, db_column='status', max_length=50, verbose_name='Status')),
                ('data_abertura_reivindicacao', models.DateTimeField(blank=True, db_column='data_abertura_reivindicacao', null=True, verbose_name='Data Abertura Reivindicação')),
                ('cpf_cnpj', models.CharField(blank=True, db_column='cpf_cnpj', max_length=50, verbose_name='CPF/CNPJ')),
                ('nome_proprietario', models.CharField(blank=True, db_column='nome_proprietario', max_length=255, verbose_name='Nome Proprietário')),
                ('nome_fantasia', models.CharField(blank=True, db_column='nome_fantasia', max_length=255, verbose_name='Nome Fantasia')),
                ('participante', models.CharField(blank=True, db_column='participante', max_length=255, verbose_name='Participante')),
                ('agencia', models.CharField(blank=True, db_column='agencia', max_length=50, verbose_name='Agência')),
                ('numero_conta', models.CharField(blank=True, db_column='numero_conta', max_length=50, verbose_name='Número da Conta')),
                ('tipo_conta', models.CharField(blank=True, db_column='tipo_conta', max_length=50, verbose_name='Tipo da Conta')),
                ('data_abertura_conta', models.DateTimeField(blank=True, db_column='data_abertura_conta', null=True, verbose_name='Data Abertura da Conta')),
                ('proprietario_da_chave_desde', models.DateTimeField(blank=True, db_column='proprietario_da_chave_desde', null=True, verbose_name='Proprietário da Chave Desde')),
                ('data_criacao', models.DateTimeField(blank=True, db_column='data_criacao', null=True, verbose_name='Data Criação')),
                ('ultima_modificacao', models.DateTimeField(blank=True, db_column='ultima_modificacao', null=True, verbose_name='Última Modificação')),
            ],
            options={
                'verbose_name': 'Chave Pix',
                'verbose_name_plural': 'Chaves Pix',
                'db_table': 'CHAVES_PIX',
            },
        ),
        migrations.CreateModel(
            name='EventoVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_void', models.BooleanField(db_column='inativo', default=False, verbose_name='Inativo')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_evento', models.CharField(blank=True, db_column='tipo_evento', max_length=255, verbose_name='Tipo do Evento')),
                ('motivo_evento', models.CharField(blank=True, db_column='motivo_evento', max_length=255, verbose_name='Motivo do Evento')),
                ('data_evento', models.DateTimeField(blank=True, db_column='data_evento', null=True, verbose_name='Data do Evento')),
                ('chave', models.CharField(blank=True, db_column='chave', max_length=255, verbose_name='Chave')),
                ('tipo_chave', models.CharField(blank=True, db_column='tipo_chave', max_length=255, verbose_name='Tipo da Chave')),
                ('cpf_cnpj', models.CharField(blank=True, db_column='cpf_cnpj', max_length=255, verbose_name='CPF/CNPJ')),
                ('nome_proprietario', models.CharField(blank=True, db_column='nome_proprietario', max_length=255, verbose_name='Nome do Proprietário')),
                ('nome_fantasia', models.CharField(blank=True, db_column='nome_fantasia', max_length=255, verbose_name='Nome Fantasia')),
                ('participante', models.CharField(blank=True, db_column='participante', max_length=255, verbose_name='Participante')),
                ('agencia', models.CharField(blank=True, db_column='agencia', max_length=50, verbose_name='Agência')),
                ('numero_conta', models.CharField(blank=True, db_column='numero_conta', max_length=50, verbose_name='Número da Conta')),
                ('tipo_conta', models.CharField(blank=True, db_column='tipo_conta', max_length=50, verbose_name='Tipo da Conta')),
                ('data_abertura_conta', models.DateTimeField(blank=True, db_column='data_abertura_conta', null=True, verbose_name='Data Abertura da Conta')),
                ('chave_pix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_vinculo', to='bacen.chavepix', verbose_name='Chave Pix')),
            ],
            options={
                'verbose_name': 'Evento Vinculo Pix CPF/CNPJ',
                'verbose_name_plural': 'Eventos Vinculo Pix CPF/CNPJ',
                'db_table': 'EVENTOS_VINCULO_PIX',
            },
        ),
        migrations.CreateModel(
            name='RequisicaoBacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_void', models.BooleanField(db_column='inativo', default=False, verbose_name='Inativo')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_requisicao', models.CharField(choices=[('1', 'Pix CPF/CNPJ'), ('2', 'Pix Chave')], db_column='tipo_requisicao', max_length=1, verbose_name='Tipo de Requisição')),
                ('termo_busca', models.CharField(blank=True, db_column='termo_busca', max_length=255, verbose_name='Termo de Busca')),
                ('motivo', models.CharField(blank=True, db_column='motivo', max_length=255, verbose_name='Motivo')),
                ('processada', models.BooleanField(db_column='processada', default=False, verbose_name='Requisição processada')),
                ('task_id', models.CharField(blank=True, db_column='task_id', max_length=255, verbose_name='ID da Tarefa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_bacen', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Requisição Bacen',
                'verbose_name_plural': 'Requisições Bacen',
                'db_table': 'REQUISICOES_BACEN',
            },
        ),
        migrations.AddField(
            model_name='chavepix',
            name='requisicao_bacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaves_pix', to='bacen.requisicaobacen', verbose_name='Requisição Bacen'),
        ),
    ]
