# Generated by Django 5.2.1 on 2025-05-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chavepix',
            name='banco',
            field=models.CharField(blank=True, db_column='banco', default='Desconhecido', max_length=255, verbose_name='Banco'),
        ),
    ]
