# Generated by Django 5.2 on 2025-04-29 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chavepix',
            options={'verbose_name': 'Chave Pix', 'verbose_name_plural': 'Chaves Pix'},
        ),
        migrations.AlterModelTable(
            name='chavepix',
            table='CHAVES_PIX',
        ),
        migrations.AlterModelTable(
            name='eventovinculo',
            table='EVENTOS_VINCULO_PIX',
        ),
    ]
