# Generated by Django 5.2 on 2025-04-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacen', '0002_alter_chavepix_options_alter_chavepix_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chavepix',
            name='chave',
            field=models.CharField(blank=True, db_column='chave', default='xpto', max_length=255, verbose_name='Chave'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chavepix',
            name='status',
            field=models.CharField(blank=True, db_column='status', max_length=50, verbose_name='Status'),
        ),
    ]
