# Generated by Django 5.2.1 on 2025-05-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacen', '0002_chavepix_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventovinculo',
            name='banco',
            field=models.CharField(blank=True, db_column='banco', default='Desconhecido', max_length=255, verbose_name='Banco'),
        ),
    ]
