# Generated by Django 5.2 on 2025-04-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacen', '0003_alter_chavepix_chave_alter_chavepix_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventovinculo',
            name='data_abertura',
        ),
        migrations.AddField(
            model_name='eventovinculo',
            name='data_abertura_conta',
            field=models.DateTimeField(blank=True, db_column='data_abertura_conta', null=True, verbose_name='Data Abertura da Conta'),
        ),
        migrations.AddField(
            model_name='eventovinculo',
            name='motivo_evento',
            field=models.CharField(blank=True, db_column='motivo_evento', max_length=255, verbose_name='Motivo do Evento'),
        ),
    ]
