# Generated by Django 5.2.1 on 2025-05-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacen', '0004_remove_eventovinculo_data_abertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaobacen',
            name='motivo',
            field=models.CharField(blank=True, db_column='motivo', max_length=255, verbose_name='Motivo'),
        ),
    ]
