# Generated by Django 5.2.1 on 2025-05-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacen', '0005_requisicaobacen_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaobacen',
            name='processada',
            field=models.BooleanField(db_column='processada', default=False, verbose_name='Requisição processada'),
        ),
    ]
