# Generated by Django 5.2.1 on 2025-05-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacen', '0006_requisicaobacen_processada'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaobacen',
            name='task_id',
            field=models.CharField(blank=True, db_column='task_id', max_length=255, verbose_name='ID da Tarefa'),
        ),
    ]
