# Generated by Django 5.2.1 on 2025-06-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaobacen',
            name='alias',
            field=models.CharField(blank=True, db_column='alias', max_length=255, verbose_name='Alias'),
        ),
    ]
