# Generated by Django 5.2.1 on 2025-05-29 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bacen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaobacen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_bacen', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='chavepix',
            name='requisicao_bacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaves_pix', to='bacen.requisicaobacen', verbose_name='Requisição Bacen'),
        ),
    ]
