# Generated by Django 5.2.1 on 2025-06-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacen', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chavepix',
            name='participante',
            field=models.JSONField(blank=True, db_column='participante', null=True, verbose_name='Participante'),
        ),
        migrations.AlterField(
            model_name='eventovinculo',
            name='participante',
            field=models.JSONField(blank=True, db_column='participante', null=True, verbose_name='Participante'),
        ),
    ]
