# Generated by Django 5.2.1 on 2025-06-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacen', '0002_requisicaobacen_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicaobacen',
            name='alias',
        ),
        migrations.AddField(
            model_name='requisicaobacen',
            name='referencia',
            field=models.CharField(blank=True, db_column='referencia', max_length=255, verbose_name='Referência'),
        ),
    ]
